### ISSUE TITLE
exception while running cronjob

### ISSUE THREAD

**Issue by anarcat** [chaica/feed2tweet#11]
found this in my cronjob logs:

```
Traceback (most recent call last):
  File "/usr/local/bin/feed2tweet", line 173, in <module>
    main()
  File "/usr/local/bin/feed2tweet", line 136, in main
    prehashtags = feed['entries'][0]['tags'][0]['term']
IndexError: list index out of range
error, unexcepted exception
list index out of range
```

it's odd because it happened only once.

it could be because of one of the PRs i wrote, but i doubt it. i think the code had #3 and #5 applied.

**Comment by chaica** [comment]
I don't have similar expections in my cron logs

**Comment by anarcat** [comment]
On 2016-01-02 04:06:43, chaica wrote:
> I don't have similar expections in my cron logs

it happened only once, it's weird.

**Comment by chaica** [comment]
In my use of feed2twee, I always add a hashtag, maybe it triggers an exception when the rss feed does not have hash tag?

**Comment by anarcat** [comment]
ah... maybe... but then i don't quite get why it would trigger only once...

**Comment by chaica** [comment]
Could not reproduce with the latest versions.
