### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by SeaWelleu** [chaica/feed2tweet#21]
```
root@debian-512mb-ams3-01:~/feed2tweet#  feed2tweet -c feed2tweet.ini
 File "/usr/local/bin/feed2tweet", line 4, in <module>
    __import__('pkg_resources').run_script('feed2tweet==0.4', 'feed2tweet')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 719, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1511, in run_script
  File "/usr/local/lib/python2.7/dist-packages/feed2tweet-0.4-py2.7.egg/EGG-INFO/scripts/feed2tweet", line 174, in <module>

  File "/usr/local/lib/python2.7/dist-packages/feed2tweet-0.4-py2.7.egg/EGG-INFO/scripts/feed2tweet", line 145, in main

  File "/usr/local/lib/python2.7/dist-packages/feedparser.py", line 356, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'tags'
```

**Comment by chaica** [comment]
Hi and thanks for your report,

From the version 0.3, feed2tweet only supports python >= 3.4. you should follow [this howto](http://feed2tweet.readthedocs.io/en/latest/install.html) in order to install it and [this one](http://feed2tweet.readthedocs.io/en/latest/use.html) to use it.

Regards,
Carl

**Comment by chaica** [comment]
basically to install it a "pip3.4 install feed2tweet" should do the job (using the root user if you are system-wide)

**Comment by SeaWelleu** [comment]
I just followed your tutorial. But I still have an error.

Command "/usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-iop4gd1e/feed2tweet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-kpboavif-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-iop4gd1e/feed2tweet/

**Comment by chaica** [comment]
Do you have setuptools installed? Is it the full error message. If not, could you copy/paste here the full error message? Thanks.

**Comment by chaica** [comment]
python3-setuptools if you use Debian-family system

**Comment by SeaWelleu** [comment]
Yes setuptools is installed on the server.

pip3.4 install feed2tweet --upgrade
Collecting feed2tweet
  Using cached feed2tweet-0.3.tar.gz
Requirement already up-to-date: feedparser in /usr/local/lib/python3.4/dist-packages (from feed2tweet)
Requirement already up-to-date: tweepy>=3.5.0 in /usr/local/lib/python3.4/dist-packages (from feed2tweet)
Requirement already up-to-date: requests>=2.4.3 in /usr/local/lib/python3.4/dist-packages (from tweepy>=3.5.0->feed2tweet)
Requirement already up-to-date: requests-oauthlib>=0.4.1 in /usr/local/lib/python3.4/dist-packages (from tweepy>=3.5.0->feed2tweet)
Requirement already up-to-date: six>=1.7.3 in /usr/local/lib/python3.4/dist-packages (from tweepy>=3.5.0->feed2tweet)
Requirement already up-to-date: oauthlib>=0.6.2 in /usr/local/lib/python3.4/dist-packages (from requests-oauthlib>=0.4.1->tweepy>=3.5.0->feed2tweet)
Building wheels for collected packages: feed2tweet
  Running setup.py bdist_wheel for feed2tweet ... error
  Complete output from command /usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-uno4e38n/feed2tweet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpq_dua3zmpip-wheel- --python-tag cp34:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/persistentlist
  copying persistentlist/main.py -> build/lib/persistentlist
  copying persistentlist/__init__.py -> build/lib/persistentlist
  running build_scripts
  creating build/scripts-3.4
  copying and adjusting feed2tweet -> build/scripts-3.4
  changing mode of build/scripts-3.4/feed2tweet from 644 to 755
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/persistentlist
  copying build/lib/persistentlist/main.py -> build/bdist.linux-x86_64/wheel/persistentlist
  copying build/lib/persistentlist/__init__.py -> build/bdist.linux-x86_64/wheel/persistentlist
  running install_data
  creating build/bdist.linux-x86_64/wheel/feed2tweet-0.3.data
  creating build/bdist.linux-x86_64/wheel/feed2tweet-0.3.data/data
  warning: install_data: setup script did not provide a directory for 'feed2tweet-sample.ini' -- installing right in 'build/bdist.linux-x86_64/wheel/feed2tweet-0.3.data/data'

  error: can't copy 'feed2tweet-sample.ini': doesn't exist or not a regular file

  ----------------------------------------
  Failed building wheel for feed2tweet
  Running setup.py clean for feed2tweet
Failed to build feed2tweet
Installing collected packages: feed2tweet
  Running setup.py install for feed2tweet ... error
    Complete output from command /usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-uno4e38n/feed2tweet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-c4ogi6oc-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/persistentlist
    copying persistentlist/main.py -> build/lib/persistentlist
    copying persistentlist/__init__.py -> build/lib/persistentlist
    running build_scripts
    creating build/scripts-3.4
    copying and adjusting feed2tweet -> build/scripts-3.4
    changing mode of build/scripts-3.4/feed2tweet from 644 to 755
    running install_lib
    running install_data
    warning: install_data: setup script did not provide a directory for 'feed2tweet-sample.ini' -- installing right in '/usr/local'

    error: can't copy 'feed2tweet-sample.ini': doesn't exist or not a regular file

    ----------------------------------------
Command "/usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-uno4e38n/feed2tweet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-c4ogi6oc-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-uno4e38n/feed2tweet/

**Comment by chaica** [comment]
ok I see what's going on, I'll release a fix asap. Should be avaialble today.

**Comment by SeaWelleu** [comment]
Ok thanks you.

**Comment by chaica** [comment]
ok, feed2tweet 0.4 is now available. I also uploaded it to pypi, so could you give it another try with pip install --upgrade please?

**Comment by SeaWelleu** [comment]
Successfully installed feed2tweet-0.4 persistentlist-0.3 !!!!!!!

Thanks.

**Comment by chaica** [comment]
And a big thanks to you because I could not reproduce it at first. Don't hesitate to star the project if you use it :)
