### ISSUE TITLE
feed cache is not used - rss items tweeted multiple times

### ISSUE THREAD

**Issue by skillfully** [chaica/feed2tweet#29]
I'm using feed2tweet with python v3.4.3. Crawling a RSS-feed ends up with multiple tweeted RSS-items. Debugging the module shows, that the cachefile has no entries after an initial run.
The path to the cache file is tested with default-settings, only filename and absolute path including filename. Everytime it's the same result - the PersistentList return an empty cache.

**Comment by chaica** [comment]
Hi and thanks for the report,

Which version of feed2tweet do you use?  Could you also give me the persistentlist version?

**Comment by skillfully** [comment]
hi,
I've tested it with feed2tweet v0.7 with following versions in a venv ...

- certifi (2016.9.26)
- feedparser (5.2.1)
- oauthlib (2.0.1)
- persistentlist (0.3)
- pip (9.0.1)
- pyshorteners (0.6.0)
- requests (2.12.1)
- requests-oauthlib (0.7.0)
- setuptools (29.0.0)
- six (1.10.0)
- tweepy (3.5.0)
- urllib3 (1.19.1)
- wheel (0.29.0)

**Comment by chaica** [comment]
Could you also provide your config file (without the twitter credentials)?
Could you try to open your .db file as above ?
Thanks

**Comment by skillfully** [comment]
Hi,
the script is running on a ubuntu 14.04.5 LTS box. The config file looks like this
```
[twitter]
consumer_key=****
consumer_secret=****
access_token=****
access_token_secret=****

[cache]
cachefile=cache.db

[rss]
uri=http://ub.hu-berlin.de/shared/news/archiv/RSS
tweet={title} {link}

;[hashtaglist]
;several_words_hashtags_list=severalwordshashtaglist.txt
```
Opening the cache file looks like that
```
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from persistentlist import PersistentList
>>> cache = PersistentList('cache', 300)
>>> cache
[]
```

There are also some inconsistencies in the definitions for the filename of the cachefile - only in a brief overview.
In the documentation for the configuration you wrote that the file extension is always "db". But the file is always generated without the extension. The module `persistentlist` looks for a path & file including the "db"-extension in `__init__.py:25` by appending these extension, but opens the file without the extension.
```
class PersistentList(object):

    def __init__(self, dbpath, maxitems):
        self.dblist = []
        self.maxitems = maxitems
        if not os.path.exists('.'.join([dbpath, 'db'])):
            self.db = shelve.open(dbpath, writeback=True)
            self.db['idlist'] = []
...
```
Last, but not least - the `confparse` module defines a fallback if no cachefilepath is defined, but defines a filename with a "dat" extension. `confparse.py:53`
```
    try:
        self.options.cachefile = config.get('cache', 'cachefile')
    except (NoOptionError, NoSectionError):
        self.options.cachefile = os.path.join(os.getenv('XDG_CACHE_HOME', '~/.cache'), 'feed2tweet.dat')
self.options.cachefile = os.path.expanduser(self.options.cachefile)
```

**Comment by chaica** [comment]
As stated in [the official documentation of PersistentList](http://persistentlist.readthedocs.io/en/latest/use.html):
```
One last important point: the name of your persistent file on the disk will be the path indicated while initializing the object, with the suffixe ”.db”, e.g if your path is /tmp/cache, the path on your disk will be /tmp/cache.db
```
So it means if you provide /var/toto/cache at the first run, the call to shelve.open() will create /var/toto/cache.db while creating the the file the first time. You have to modify the path in the configuration file after that.
```
>>> import shelve
>>> db = shelve.open('cache', writeback=True)
>>> db.close()
$ ls -ltr
...
-rw-r--r--  1 chaica chaica    12288 Nov 30 16:21 cache.db
```

This behaviour will be improved in the next version of PersistentList. I'm opening a bug report for the default cache file. This code is legacy code and should be fixed.

**Comment by chaica** [comment]
Hi @skillfully 

Could you try both persistentlist 0.4 and feed2tweet 0.8 to see if the problem remains?  Could you also only use absolute paths in the .ini file ? Let me know.

**Comment by skillfully** [comment]
Hi,
after a fresh install with persistentlist 0.4 and feed2tweet 0.8 the problem remains.
The cache file is created without db-extension and is not filled with pushed rss-feed-items.

**Comment by chaica** [comment]
Is libgdm installed on your system? For me:
```
dpkg -l |grep -i dbm
ii  libgdbm3:amd64                        1.8.3-14                             amd64        GNU dbm database routines (runtime version)
```

**Comment by skillfully** [comment]
it's installed
```
$ dpkg -l |grep -i dbm
ii  libgdbm3:amd64                                        1.8.3-12build1                                      amd64        GNU dbm database routines (runtime version)
ii  python-gdbm                                           2.7.5-1ubuntu1                                      amd64        GNU dbm database support for Python
ii  python3-gdbm:amd64                                    3.4.3-1~14.04.2                                     amd64        GNU dbm database support for Python 3.x
```

**Comment by chaica** [comment]
For your issue about #41 with the tweet containing <feed2tweet.removeduplicates.RemoveDuplicates object at 0x7f4a64689208>, it should be fixed now. I'll release 0.9 shortly.

**Comment by chaica** [comment]
Still the bug with the 0.9?

**Comment by skillfully** [comment]
Apologize for the late feedback - version 0.9 is working without errors.
Thanks!
