### ISSUE TITLE
cache file setting should support tilde expansion

### ISSUE THREAD

**Issue by anarcat** [chaica/feed2tweet#45]
i have the following config file snippet i was using with feed2tweet 0.1:

```
[cache]
cachefile=~/.cache/feed2tweet.dat
```

this used to work then, but with the latest release, I get this:

```
[1121]anarcat@curie:feed2tweet1$ ./feed2tweet.py -c ~/.config/feed2tweet.ini -n --syslog -r https://anarc.at/blog/index.rss
You should provide an absolute path to the cache file in the [cache] section
```

I had to change this to:

```
[cache]
cachefile=/home/anarcat/.cache/feed2tweet.dat
```

this seems counter-intuitive.

**Comment by chaica** [comment]
Yes you're right, the expansion of tilde should be realized internally. I'll fix it
