### ISSUE TITLE
config file default doesn't work

### ISSUE THREAD

**Issue by anarcat** [chaica/feed2tweet#46]
the help output says:

```
  -c FILE [FILE ...], --config FILE [FILE ...]
                        Location of config file (default:
                        ~/.config/feed2tweet.ini)
```

yet, if i run feed2tweet without the `-c` argument, i get this:

```
$ ./feed2tweet.py  -n  -r https://anarc.at/blog/index.rss 
You should provide an absolute path for the config file
```

this seems contrary to the documentation, and a regression from the 0.1 release.

**Comment by chaica** [comment]
Yes we had an issue with it earlier and I'm not using it myself. If you want to implement it correctly, go ahead, otherwise I'll fix the help and keep it as it is.
