### ISSUE TITLE
strange message posted by feed2tweet "feed2tweet.removeduplicates.RemoveDuplicates"

### ISSUE THREAD

**Issue by danc** [chaica/feed2tweet#50]
Bonjour,
J'ai été étonné par le tweet produit par feed2tweet 0.8 : 

https://twitter.com/tintouli/status/824629322686271488

Je pense que la circonstance est la suivante : 
je reposte à partir du fil rss suivant : 

http://stream.logpickr.com/profile/daniel?_t=rss
qui provient du logiciel withknown.com qui génère divers flux RSS.

Hier, sur un article donné (http://stream.logpickr.com/2017/explore-salesforce-crm-connected-data-with-linkurious---linkurious) j'ai changé un hashtag (ajouté #salesforce) ce qui a du provoquer un changement dans le flux, que feed2tweet a peut-être considéré comme un doublon, d'ou le message d'erreur ?
Ce qui est gênant, c'est que ce message s'est transformé en tweet ...

J'ai aussi une autre instance tintouli.withknown.com   qui pourrait servir à faire d'autres tests.

**Comment by chaica** [comment]
English is a better practice for the bug reports ;)

This bug was fixed by 0.9. See #41 for the details. Please upgrade to fix the issue.
