### ISSUE TITLE
Duplicate tweets!

### ISSUE THREAD

**Issue by mR12KL** [chaica/feed2tweet#52]
Hi,

I have 41 RSS feeds, each with 26 items. feed2tweet has been catching up with each feed, but now its repeating entries and not catching duplicates.

Twitter: https://twitter.com/masterleakers (if you hold down the end button until all the tweets are shown, some repeat if you CTRL+F them

**Config File:**
`[twitter]
consumer_key=omitted
consumer_secret=omitted
access_token=omitted
access_token_secret=omitted

[cache]
cachefile=/usr/lib/python2.6/site-packages/feed2tweet
cache_limit=10000

[rss]
uri_list: /var/www/html/kl/rsslist.txt
tweet: {title}
title_pattern: Open Source
title_pattern_case_sensitive: true
no_uri_pattern_no_global_pattern=true

;[hashtaglist]
;several_words_hashtags_list: /usr/lib/games/hashtags.txt`

**Crontab Cronjob**
0 * * * * root feed2tweet -c /var/www/html/kl/feed2tweet.ini

**RSS List**
http://kingdom-leaks.com/index.php?/forums/forum/46-previews.xml/
http://kingdom-leaks.com/index.php?/forums/forum/77-upcoming-singles.xml/
http://kingdom-leaks.com/index.php?/forums/forum/47-core-news.xml/
http://kingdom-leaks.com/index.php?/forums/forum/48-rock-news.xml/
http://kingdom-leaks.com/index.php?/forums/forum/49-metal-news.xml/
http://kingdom-leaks.com/index.php?/forums/forum/50-pop-punk-news.xml/
http://kingdom-leaks.com/index.php?/forums/forum/52-electronic-news.xml/
http://kingdom-leaks.com/index.php?/forums/forum/51-pop-news.xml/
http://kingdom-leaks.com/index.php?/forums/forum/38-videos.xml/
http://kingdom-leaks.com/index.php?/forums/forum/37-compilations.xml/
http://kingdom-leaks.com/index.php?/forums/forum/36-oldies.xml/
http://kingdom-leaks.com/index.php?/forums/forum/63-discographies.xml/
http://kingdom-leaks.com/index.php?/forums/forum/30-electronic.xml/
http://kingdom-leaks.com/index.php?/forums/forum/61-emo.xml/
http://kingdom-leaks.com/index.php?/forums/forum/40-acoustic.xml/
http://kingdom-leaks.com/index.php?/forums/forum/29-country.xml/
http://kingdom-leaks.com/index.php?/forums/forum/41-singersongwriter.xml/
http://kingdom-leaks.com/index.php?/forums/forum/42-miscellaneous.xml/
http://kingdom-leaks.com/index.php?/forums/forum/33-pop-punk.xml/
http://kingdom-leaks.com/index.php?/forums/forum/32-pop.xml/
http://kingdom-leaks.com/index.php?/forums/forum/34-punk.xml/
http://kingdom-leaks.com/index.php?/forums/forum/19-hip-hoprap.xml/
http://kingdom-leaks.com/index.php?/forums/forum/68-rbsoul.xml/
http://kingdom-leaks.com/index.php?/forums/forum/15-indie.xml/
http://kingdom-leaks.com/index.php?/forums/forum/16-indie-rock.xml/
http://kingdom-leaks.com/index.php?/forums/forum/17-indie-pop.xml/
http://kingdom-leaks.com/index.php?/forums/forum/11-metal.xml/
http://kingdom-leaks.com/index.php?/forums/forum/9-alternative-metal.xml/
http://kingdom-leaks.com/index.php?/forums/forum/12-progressive-metal.xml/
http://kingdom-leaks.com/index.php?/forums/forum/25-death-metal.xml/
http://kingdom-leaks.com/index.php?/forums/forum/69-post-metalscreamoblack-metal.xml/
http://kingdom-leaks.com/index.php?/forums/forum/10-rock.xml/
http://kingdom-leaks.com/index.php?/forums/forum/5-alternative-rock.xml/
http://kingdom-leaks.com/index.php?/forums/forum/6-progressive-rock.xml/
http://kingdom-leaks.com/index.php?/forums/forum/62-pop-rock.xml/
http://kingdom-leaks.com/index.php?/forums/forum/31-punk-rock.xml/
http://kingdom-leaks.com/index.php?/forums/forum/22-post-hardcore.xml/
http://kingdom-leaks.com/index.php?/forums/forum/23-metalcore.xml/
http://kingdom-leaks.com/index.php?/forums/forum/65-hardcore.xml/
http://kingdom-leaks.com/index.php?/forums/forum/24-deathcore.xml/
http://kingdom-leaks.com/index.php?/forums/forum/27-easycore.xml/
http://kingdom-leaks.com/index.php?/forums/forum/26-misc-core.xml/

**Comment by chaica** [comment]
Hi, thanks for your feedback. I'm investigating and I'll let you know asap.

**Comment by chaica** [comment]
Thanks for the complete bug report. To debug, can I ask you 2 direct urls of duplicated tweets and the 2 rss feeds they are from, in order I inspect these rss feeds? It seems to be related to the ids of the entries in the rss feeds and storing these ids in the cache file

**Comment by mR12KL** [comment]
Not sure I completely understand what you're asking for, but is this what you want?

Duplicate tweets:
https://twitter.com/masterleakers/status/848596172059103232
https://twitter.com/masterleakers/status/848574056907640837

Both originated from the **SAME** RSS Feed:
http://kingdom-leaks.com/index.php?/forums/forum/9-alternative-metal.xml/

Should be the 4th entry down.

I just ran it again, and it shows the same message: http://i.imgur.com/U5L57yP.png / it appears that its not catching the duplicates at all, because it just posted 40 new tweets with this command and all of them had already been posted before.

Thanks!

**Comment by mR12KL** [comment]
Any word on this?

**Comment by chaica** [comment]
not forgetting but I was really busy with the launch of one of my new projects. having a look (again) today or tomorrow. Sorry :(

**Comment by mR12KL** [comment]
Thanks! I think I have a workaround. Ill just create 41 ini files and run them all separately. The only problem I may run into is running them all at once. Can feed2tweet process multiple ini files at once? If so, how would I go about running them all?

**Comment by chaica** [comment]
For multiple ini files, it should be as simple as launching:
```
$ feed2tweet -c /etc/feed2tweets/
```
where all your ini files are in /etc/feed2tweets/ 
```
$ feed2tweet -c /etc/feed2tweet/*.ini
```
should also work. You can test without actually posting with the **--dry-run** command line option.

**Comment by mR12KL** [comment]
Thanks! Say I wanted to grab the first entry from each feed every minute, and if its new, post it. Would I set the cache size to 1? (provided I have separate .db files for each ini file)

**Comment by chaica** [comment]
Cache size is related to the size of your RSS feeds, e.g you have 100 rss feeds using the same cache file, it is maybe 10 or 20 entries by RSS * 100 => cachefile needs to be greater than 1000 or 2000.

hmm, currently feed2tweet will post every new entries each time your execute it. what's the need of only one entry by minute ? How do you manage if you have 2 entries in a minute and the next minute another entry. Do you skip the second one ?

**Comment by mR12KL** [comment]
Well unfortunately feed2tweet does not only post new entries, its not catching the duplicates. hence my workaround. each of my RSS feeds has 26 entries. I do not want over a thousand tweets flooding my twitter because feed2tweet needs to "catch up" on all the new ones. i want to start realtime.

regardless, this is the only program out there that actually works and has active support, so i thank you for that. 

Back to my question, sorry. For 1 single feed, that holds 26 entries, I should make my cache_size 26 or larger?

**Comment by chaica** [comment]
make it 100 (default) if only one single RSS.

**Comment by mR12KL** [comment]
ok, thanks for your help! ill get back to you on if the workaround worked or not

**Comment by chaica** [comment]
hmmm ok I just parsed with the feedparse python library all of your RSS feeds. I get all entries ids and they are all unique, meaning you should not have doubles, whatever happens. Could you launch the following commands please:

```
$ python3
>>> import shelve
>>> test = shelve.open('test')
>>> test.close()
>>> import dbm
>>> dbm.whichdb('test')
```
Thanks

**Comment by mR12KL** [comment]
i ran it on python3.6:


[root@server ~]# python3.6
Python 3.6.1 (default, Apr  1 2017, 20:26:50)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shelve
>>> test = shelve.open('test')
>>> import dbm
>>> dbm.whichdb('test')
'dbm.gnu'

**Comment by chaica** [comment]
ok now I understand what's going on. Will be able to fix it soon.

**Comment by mR12KL** [comment]
Have no idea what that bit of code means, but hey, thanks!

**Comment by chaica** [comment]
Feed2tweet was using the Python persistentlist library to store the cache file. This library uses the standard library dbm module which is platforme-dependent and not generating the same kind of files depending on your installation.

So I just removed this dependency and coded a custom cache. It should be ok now. Let me know.

**Comment by mR12KL** [comment]
The tweets are still repeating! Maybe I didn't reinstall feed2tweet correctly. Sorry, could you walk me through how to install it? The first time, I installed it with just pip (Python 2.6) And when I just did it now, i ran "pip3.6 install feed2tweet" and then ran:

`* * * * * root feed2tweet -c /var/www/html/kl/misc/feed2tweet/`

in my crontab

The tweets are currently flooding my feed right now @ https://twitter.com/masterleakers and some are being posted 3-4 even 5 times. Ughhhh

**Comment by chaica** [comment]
Ok, 
you need to uninstall feed2tweet. I suppose here you only use python 2.7 and python 3.6:
```
# pip2.7 uninstall feed2tweet
# pip3.6 uninstall feed2tweet
```
then you need to reinstall feed2tweet with python3
```
# pip3.7 install feed2tweet --upgrade
```
Check if you have the latest version:
```
# feed2tweet --version
1.1
```
Now you have to remove your cache file (modify the path):
```
$ rm -f /var/lib/feed2tweet/cache.db
```
Ok you're now ready to rebuild your cache. It means we get all your RSS feeds without actually posting the to Twitter with the**--populate-cache** command line option. We also use **--dry-run** in order to check if feed2tweet gets the feeds without storing or posting them:
```
$ feed2tweet --dry-run --populate-cache -c /etc/feed2tweet/feed2tweet.ini
```
If you read that new entries should have been added, that's great. We're now ready to populate the cache:
```
$ feed2tweet --populate-cache -c /etc/feed2tweet/feed2tweet.ini
```
Ok normally a new cache file should appear. check it it exists at the path specified in your configuration.
Now you're ready to only post the new entries if they come up with the following command:
```
$ feed2tweet -c /etc/feed2tweet/feed2tweet.ini
```

**Comment by mR12KL** [comment]
I followed your steps exactly, but the issue still persists. It's alright though, I'm sure its because of my lack of experience. I haven't seen any other bugs reported for duplicate tweets. I think I'm gonna abandon the whole Twitter track for now, maybe revisit it later.
