### ISSUE TITLE
send as many tags as possible

### ISSUE THREAD

**Issue by anarcat** [chaica/feed2tweet#6]
it seems we now send only the first tag found. i would rather pick all of them, or add a way to pick a  random one because my tags are sorted before generating the feed, which makes feed2tweet pick mostly the same tag all the time, since i often post under `debian-planet`, which is fairly low alphabetically...

**Comment by chaica** [comment]
Actually it is the first two hash tags when no hash tags withe several words is used:
```
'hashtag': ' '.join(['#%s' % i for i in entry['tags'][0]['term'].split()[:2]]),
```
I guess this limitation of inherited from rss2twitter should be removed, but you have to consider the length of the string to tweet in order to stay below the Twitter tweet character limitation.

**Comment by anarcat** [comment]
how about picking random ones? or picking as much as possible while staying under the 140 char limit?
