### ISSUE TITLE
do not use pickle to store state

### ISSUE THREAD

**Issue by anarcat** [chaica/feed2tweet#8]
pickle is susceptible to corruption when interrupted, plus it's really unsafe to run it.

what we need is just a string, the feed entry `id`. this could be stored in a text file - why do we store the whole feed entry?

we could transition over to a new cache file - we could simply find the existing cache file, parse it if it exists, then delete it and write the new format to transition correctly.

i'd be happy to implement this if you are open to the idea.

**Comment by anarcat** [comment]
if we really need to store the whole entry object, use something safer like JSON or XML.

**Comment by anarcat** [comment]
see also http://danluu.com/file-consistency/

speaking of which... locking maybe?

**Comment by chaica** [comment]
I'm really open to this idea, using pickle is an inheritage from rss2twitter. And I don't see the use of this in the current situation.

**Comment by anarcat** [comment]
i'd be happy to implement this, but i'll wait for #7 to land because it would create even more conflicts... i already have to port for #4 ...

**Comment by chaica** [comment]
Solved by release 0.4
